.TH "contagem_maos.c" 3 "Wed Dec 3 2014" "Version 2.0" "Dominó, time 1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
contagem_maos.c \- 
.PP
Conta o total de pontos, para cada jogador, contigo na sua mão\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include 'minhas_funcoes\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBcontagem_maos\fP (int mao_1[], int mao_2[], int mao_3[], int mao_4[])"
.br
.RI "\fIConta o total de pontos, para cada jogador, contigo na sua mão\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Conta o total de pontos, para cada jogador, contigo na sua mão\&. 

Essa função verifica qual jogador tem menos pontos (e portanto *o vencedor) após todos os quatro terem tocado\&. 
.PP
\fBVersion:\fP
.RS 4
3\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
03/12/2014 
.RE
.PP
\fBAuthor:\fP
.RS 4
MAXIMILIANO ADOLFO 
.RE
.PP
\fBCopyright:\fP
.RS 4
(c) 2014 GNU GPL v3 *This program is free software; you can redistribute it and/or modify *it under the terms of the GNU General Public License as published by *the Free Software Foundation; either version 2 of the License, or (at your option) any later version\&.
.RE
.PP
*This program is distributed in the hope that it will be useful, *but WITHOUT ANY WARRANTY; without even the implied warranty of *MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the *GNU General Public License for more details\&.
.PP
*You should have received a copy of the GNU General Public License *along with this program; if not, write to the *Free Software Foundation, Inc\&., *59 Temple Place - Suite 330, Boston, MA 02111-1307, USA\&. *Or read it online at <http://www.gnu.org/licenses/>\&. 
.PP
Definition in file \fBcontagem_maos\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int contagem_maos (intmao_1[], intmao_2[], intmao_3[], intmao_4[])"

.PP
Conta o total de pontos, para cada jogador, contigo na sua mão\&. Essa função verifica qual jogador tem menos pontos (e portanto *o vencedor) após todos os quatro terem tocado\&. 
.PP
\fBParameters:\fP
.RS 4
\fImao_1\fP Armazena as peças da mão do jogador 1\&. 
.br
\fImao_2\fP Armazena as peças da mão do jogador 2\&. 
.br
\fImao_3\fP Armazena as peças da mão do jogador 3\&. 
.br
\fImao_4\fP Armazena as peças da mão do jogador 4\&. 
.RE
.PP

.PP
Definition at line 62 of file contagem_maos\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Dominó, time 1 from the source code\&.
