.TH "md_README" 3 "Wed Dec 3 2014" "Version 2.0" "Dominó, time 1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_README \- domino001 
Trabalho final de Informática - Time 1
.PP
Lucas Canejo Jurema
.PP
Rodrigo Borba
.PP
Marcus Vinicius Luna Dias
.PP
Regina Gomes
.PP
Lucas Pereira Calado
.PP
Lucas Borges
.PP
Maximiliano Adolfo Quirino Costa
.PP
Viviane Sanguinett
.PP
Gabriel Alfaya Sá Barreto
.PP
Arnold Felix Pereira 
