.TH "monta_pm.c" 3 "Wed Dec 3 2014" "Version 2.0" "Dominó, time 1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
monta_pm.c \- 
.PP
Monta as pontas da mesa\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmonta_pm\fP (int rodada, int jogador, int p_jog, int peca, int pm[], char ver_b)"
.br
.RI "\fIMonta as pontas da mesa\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Monta as pontas da mesa\&. 

Imprime na tela os valores das pontas das peças localizadas nas duas *extremidades da cadeia de peças\&. 
.PP
\fBVersion:\fP
.RS 4
3\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
03/12/2014 
.RE
.PP
\fBAuthor:\fP
.RS 4
MAXIMILIANO ADOLFO 
.RE
.PP
\fBCopyright:\fP
.RS 4
(c) 2014 GNU GPL v3 *This program is free software; you can redistribute it and/or modify *it under the terms of the GNU General Public License as published by *the Free Software Foundation; either version 2 of the License, or (at your option) any later version\&.
.RE
.PP
*This program is distributed in the hope that it will be useful, *but WITHOUT ANY WARRANTY; without even the implied warranty of *MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the *GNU General Public License for more details\&.
.PP
*You should have received a copy of the GNU General Public License *along with this program; if not, write to the *Free Software Foundation, Inc\&., *59 Temple Place - Suite 330, Boston, MA 02111-1307, USA\&. *Or read it online at <http://www.gnu.org/licenses/>\&. 
.PP
Definition in file \fBmonta_pm\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int monta_pm (introdada, intjogador, intp_jog, intpeca, intpm[], charver_b)"

.PP
Monta as pontas da mesa\&. Imprime na tela os valores das pontas das peças localizadas nas duas *extremidades da cadeia de peças\&. 
.PP
\fBParameters:\fP
.RS 4
\fIrodada\fP Armazena a rodada corrente\&. 
.br
\fIjogador\fP Armazena o jogador corrente\&. 
.br
\fIp_jog\fP Registra o jogador que inicia a partida\&. 
.br
\fIpeca\fP Armazena a peça\&. 
.br
\fIpm\fP Armazena separadamente o valor das extremidades da mesa\&. 
.br
\fIver_b\fP Contém a versão do jogo, se é a beta ou não\&. 
.RE
.PP

.PP
Definition at line 63 of file monta_pm\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Dominó, time 1 from the source code\&.
