.TH "mostra_mao.c" 3 "Wed Dec 3 2014" "Version 2.0" "Dominó, time 1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mostra_mao.c \- 
.PP
Mostra a mão de um jogador\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmostra_mao\fP (int mao[])"
.br
.RI "\fIMostra a mão de um jogador\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Mostra a mão de um jogador\&. 

Imprime na tela a mão de um jogador\&. 
.PP
\fBVersion:\fP
.RS 4
3\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
03/12/2014 
.RE
.PP
\fBAuthor:\fP
.RS 4
MAXIMILIANO ADOLFO 
.RE
.PP
\fBCopyright:\fP
.RS 4
(c) 2014 GNU GPL v3 *This program is free software; you can redistribute it and/or modify *it under the terms of the GNU General Public License as published by *the Free Software Foundation; either version 2 of the License, or (at your option) any later version\&.
.RE
.PP
*This program is distributed in the hope that it will be useful, *but WITHOUT ANY WARRANTY; without even the implied warranty of *MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the *GNU General Public License for more details\&.
.PP
*You should have received a copy of the GNU General Public License *along with this program; if not, write to the *Free Software Foundation, Inc\&., *59 Temple Place - Suite 330, Boston, MA 02111-1307, USA\&. *Or read it online at <http://www.gnu.org/licenses/>\&. 
.PP
Definition in file \fBmostra_mao\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int mostra_mao (intmao[])"

.PP
Mostra a mão de um jogador\&. Imprime na tela a mão de um jogador\&. 
.PP
\fBParameters:\fP
.RS 4
\fImao\fP Armazena as peças da mão de um jogador\&. 
.RE
.PP

.PP
Definition at line 62 of file mostra_mao\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Dominó, time 1 from the source code\&.
